services:
  main:
    build:
      context: main
      dockerfile: Dockerfile
    container_name: main
    restart: unless-stopped
    tty: true
    environment:
      - PORT=3000
    env_file:
      - .atlas.env
    working_dir: /app/main
    ports:
      - "3000:3000"
    volumes:
      - ./main:/app/main

